### ISSUE TITLE
Add proper social media Previews

### ISSUE THREAD

**Issue by MasterObvious** [hackcambridge/hc2020-prototype#88]
<img width="506" alt="Screenshot 2019-12-10 at 14 37 41" src="https://user-images.githubusercontent.com/13217875/70541554-25e79b00-1b5f-11ea-86e3-ab7ba47a8df7.png">

As we can see above, we have some issues with previews on social media. Let's make sure that everything looks pretty so advertising is fine

**Comment by HarriBellThomas** [comment]
<img width="534" alt="Screenshot 2019-12-10 at 15 30 34" src="https://user-images.githubusercontent.com/3679819/70543276-0d2cb480-1b62-11ea-90eb-9ef70b5b7ead.png">
